In [1]:
import numpy as np
import os
from pathlib import Path

In [2]:
pwd

'd:\\Computer_Vision\\pouravi_computer_vision_project\\cotton_disease_classification\\research'

In [3]:
os.chdir("../")

In [4]:
import tensorflow as tf

In [5]:
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image

In [6]:
model = tf.keras.models.load_model(Path("artifacts/training/inceptionV3.h5"))

In [15]:
img=image.load_img("artifacts/data_ingestion/test/fresh cotton plant/dsd (223).jpg",target_size=(224,224))

In [16]:
x=image.img_to_array(img)
x

array([[[ 57., 138.,  18.],
        [ 55., 136.,  16.],
        [ 69., 142.,  25.],
        ...,
        [100., 158.,  81.],
        [106., 160.,  76.],
        [101., 155.,  77.]],

       [[ 68., 145.,  15.],
        [ 74., 150.,  28.],
        [ 64., 138.,  17.],
        ...,
        [143., 188.,  85.],
        [172., 199.,  84.],
        [107., 152.,  69.]],

       [[ 64., 139.,  10.],
        [ 51., 128.,   0.],
        [ 92., 167.,  40.],
        ...,
        [143., 185.,  57.],
        [132., 175.,  68.],
        [ 96., 149.,  57.]],

       ...,

       [[ 60.,  53.,  35.],
        [ 66.,  57.,  42.],
        [ 55.,  46.,  29.],
        ...,
        [ 70., 117.,  49.],
        [ 72., 122.,  49.],
        [ 76., 128.,  54.]],

       [[ 67.,  60.,  42.],
        [ 69.,  62.,  44.],
        [ 87.,  78.,  61.],
        ...,
        [ 77., 127.,  58.],
        [ 82., 132.,  61.],
        [ 74., 126.,  54.]],

       [[ 63.,  56.,  38.],
        [ 76.,  69.,  51.],
        [ 78.,  

In [17]:
x.shape

(224, 224, 3)

In [18]:
x=x/255
x

array([[[0.22352941, 0.5411765 , 0.07058824],
        [0.21568628, 0.53333336, 0.0627451 ],
        [0.27058825, 0.5568628 , 0.09803922],
        ...,
        [0.39215687, 0.61960787, 0.31764707],
        [0.41568628, 0.627451  , 0.29803923],
        [0.39607844, 0.60784316, 0.3019608 ]],

       [[0.26666668, 0.5686275 , 0.05882353],
        [0.2901961 , 0.5882353 , 0.10980392],
        [0.2509804 , 0.5411765 , 0.06666667],
        ...,
        [0.56078434, 0.7372549 , 0.33333334],
        [0.6745098 , 0.78039217, 0.32941177],
        [0.41960785, 0.59607846, 0.27058825]],

       [[0.2509804 , 0.54509807, 0.03921569],
        [0.2       , 0.5019608 , 0.        ],
        [0.36078432, 0.654902  , 0.15686275],
        ...,
        [0.56078434, 0.7254902 , 0.22352941],
        [0.5176471 , 0.6862745 , 0.26666668],
        [0.3764706 , 0.58431375, 0.22352941]],

       ...,

       [[0.23529412, 0.20784314, 0.13725491],
        [0.25882354, 0.22352941, 0.16470589],
        [0.21568628, 0

In [19]:
from tensorflow.keras.applications.inception_v3 import preprocess_input

In [20]:
import numpy as np
x=np.expand_dims(x,axis=0)
img_data=preprocess_input(x)
img_data.shape

(1, 224, 224, 3)

In [21]:
model.predict(img_data)

1/1 [==============================] - 0s 129ms/step


array([[0.95277894, 0.00662976, 0.02957789, 0.01101347]], dtype=float32)

In [23]:
np.argmax(model.predict(img_data), axis=1)

1/1 [==============================] - 0s 119ms/step


array([0], dtype=int64)

In [38]:
a==1

array([False])